
import { Company } from './types';

// In production, this data would come from a JSON file generated by PHP from Excel
export const COMPANIES: Company[] = [
  {
    id: '1',
    name: 'Tenuta del Friuli',
    category: 'Cantina',
    description: 'Storica cantina nel cuore del Collio, specializzata in vini bianchi autoctoni e macerati.',
    address: 'Via delle Vigne 12, Cormons (GO)',
    lat: 46.293,
    lng: 13.468,
    products: ['Friulano', 'Ribolla Gialla', 'Malvasia'],
    website: 'https://terrefvg.it',
    phone: '+39 0481 000001',
    email: 'info@tenutafriuli.mock',
    imageUrl: 'https://picsum.photos/800/600?random=1',
    features: ['Degustazioni', 'Visita Vigna', 'Vendita Diretta'],
    socials: {
      facebook: 'https://facebook.com',
      instagram: 'https://instagram.com'
    },
    gallery: [
      'https://picsum.photos/400/300?random=10',
      'https://picsum.photos/400/300?random=11'
    ],
    bookingUrl: 'mailto:prenotazioni@tenutafriuli.mock',
    reviews: [
      { id: 'r1', author: 'Mario Rossi', rating: 5, text: 'Vini eccezionali e accoglienza calorosa.', date: '2023-10-15' },
      { id: 'r2', author: 'Anna Bianchi', rating: 4, text: 'Bellissima location per un aperitivo al tramonto.', date: '2023-09-20' }
    ],
    openingHours: {
      monday: "09:00-18:00",
      tuesday: "09:00-18:00",
      wednesday: "09:00-18:00",
      thursday: "09:00-18:00",
      friday: "09:00-19:00",
      saturday: "10:00-19:00",
      sunday: "Chiuso"
    }
  },
  {
    id: '2',
    name: 'Agriturismo Al Melograno',
    category: 'Agriturismo',
    description: 'Cucina tipica friulana con ingredienti a km 0 e camere immerse nella natura.',
    address: 'Strada di Campagna 4, Cividale del Friuli (UD)',
    lat: 46.093,
    lng: 13.430,
    products: ['Salumi', 'Formaggi', 'Frico'],
    website: 'https://terrefvg.it',
    phone: '+39 0432 000002',
    email: 'info@melograno.mock',
    imageUrl: 'https://picsum.photos/800/600?random=2',
    features: ['Pernottamento', 'Ristorante', 'Fattoria Didattica'],
    socials: {
      facebook: 'https://facebook.com'
    },
    gallery: [
      'https://picsum.photos/400/300?random=12',
      'https://picsum.photos/400/300?random=13'
    ],
    reviews: [
      { id: 'r3', author: 'Luca Verdi', rating: 5, text: 'Il miglior frico della zona!', date: '2023-11-01' }
    ],
    openingHours: {
      thursday: "18:00-23:00",
      friday: "18:00-23:00",
      saturday: "12:00-15:00, 18:00-23:00",
      sunday: "12:00-16:00"
    }
  },
  {
    id: '3',
    name: 'Caseificio Valli del Natisone',
    category: 'Produttore',
    description: 'Produzione artigianale di formaggi di malga e latticini freschi secondo tradizione.',
    address: 'Via Montagna 8, San Pietro al Natisone (UD)',
    lat: 46.120,
    lng: 13.485,
    products: ['Montasio DOP', 'Latteria', 'Ricotta Affumicata'],
    phone: '+39 0432 000003',
    imageUrl: 'https://picsum.photos/800/600?random=3',
    features: ['Vendita Diretta', 'Visita Produzione'],
    reviews: [],
    openingHours: {
      monday: "08:00-13:00",
      tuesday: "08:00-13:00",
      wednesday: "08:00-13:00",
      thursday: "08:00-13:00",
      friday: "08:00-13:00",
      saturday: "08:00-13:00"
    }
  },
  {
    id: '4',
    name: 'Osteria Antico Borgo',
    category: 'Ristorazione',
    description: 'Un viaggio nei sapori della tradizione in un ambiente rustico e accogliente.',
    address: 'Piazza Centrale 1, Palmanova (UD)',
    lat: 45.906,
    lng: 13.310,
    products: ['Vini Locali', 'Piatti Tipici'],
    website: 'https://terrefvg.it',
    imageUrl: 'https://picsum.photos/800/600?random=4',
    features: ['Pranzo', 'Cena', 'Eventi'],
    socials: {
      instagram: 'https://instagram.com'
    },
    bookingUrl: 'https://terrefvg.it/prenota',
    reviews: [
      { id: 'r4', author: 'Giulia Neri', rating: 3, text: 'Cibo buono, servizio un po\' lento.', date: '2023-08-10' }
    ],
    openingHours: {
      monday: "11:00-15:00, 18:00-23:00",
      wednesday: "11:00-15:00, 18:00-23:00",
      thursday: "11:00-15:00, 18:00-23:00",
      friday: "11:00-15:00, 18:00-24:00",
      saturday: "11:00-15:00, 18:00-24:00",
      sunday: "11:00-16:00"
    }
  },
  {
    id: '5',
    name: 'Vigneti del Carso',
    category: 'Cantina',
    description: 'Vini eroici coltivati sulla roccia carsica, con vista sul golfo di Trieste.',
    address: 'Loc. Rupinpiccolo, Sgonico (TS)',
    lat: 45.730,
    lng: 13.760,
    products: ['Terrano', 'Vitovska'],
    website: 'https://terrefvg.it',
    imageUrl: 'https://picsum.photos/800/600?random=5',
    features: ['Degustazioni Panoramiche', 'Trekking in Vigna'],
    gallery: [
      'https://picsum.photos/400/300?random=15',
      'https://picsum.photos/400/300?random=16',
      'https://picsum.photos/400/300?random=17'
    ],
    socials: {
      facebook: 'https://facebook.com',
      instagram: 'https://instagram.com'
    },
    reviews: [
      { id: 'r5', author: 'Marco Polo', rating: 5, text: 'Vista mozzafiato e vino superbo.', date: '2023-07-05' }
    ],
    openingHours: {
      friday: "16:00-20:00",
      saturday: "10:00-20:00",
      sunday: "10:00-20:00"
    }
  }
];

export const INITIAL_LAT = 46.06;
export const INITIAL_LNG = 13.23;
export const INITIAL_ZOOM = 9;
